sonar.projectKey=N4ksu_Examify11
sonar.organization=n4ksu
sonar.host.url=https://sonarcloud.io

sonar.sources=examify_flutter/lib,examify-backend/app
sonar.sourceEncoding=UTF-8

sonar.exclusions=**/test/**,**/vendor/**,**/node_modules/**,**/build/**,**/.dart_tool/**
