sonar.projectKey=N4ksu_Examify11
sonar.organization=n4ksu
sonar.host.url=https://sonarcloud.io

# ✅ Include BOTH projects
sonar.sources=examify_flutter/lib,examify-backend/app

# Optional but recommended
sonar.exclusions=**/test/**,**/vendor/**,**/node_modules/**

# Encoding
sonar.sourceEncoding=UTF-8
