sonar.projectKey=N4ksu_Examify11
sonar.organization=n4ksu
sonar.host.url=https://sonarcloud.io

# Source folders
sonar.sources=examify_flutter/lib,examify-backend/app

# General exclusions
sonar.exclusions=**/test/**,**/vendor/**,**/node_modules/**,**/build/**,**/.dart_tool/**,\
examify_flutter/lib/features/assessment/take/take_assessment_screen.dart,\
examify_flutter/lib/features/classroom/classroom_detail_screen.dart,\
examify_flutter/lib/features/classroom/stream_tab.dart

# Encoding
sonar.sourceEncoding=UTF-8

# Coverage report paths
sonar.dart.lcov.reportPaths=examify_flutter/coverage/lcov.info
sonar.php.coverage.reportPaths=examify-backend/coverage.xml

# Coverage exclusions
sonar.coverage.exclusions=\
examify_flutter/lib/main.dart,\
examify_flutter/lib/**/screens/**,\
examify_flutter/lib/**/widgets/**,\
examify_flutter/lib/**/models/**,\
examify_flutter/lib/**/providers/**,\
examify_flutter/lib/**/generated/**,\
examify_flutter/lib/**/*.g.dart,\
examify_flutter/lib/**/*.freezed.dart,\
examify-backend/app/Http/Controllers/**,\
examify-backend/app/Models/**,\
examify-backend/app/Providers/**,\
examify-backend/app/Exceptions/**

# Duplication exclusions
sonar.cpd.exclusions=\
examify_flutter/lib/**/screens/**,\
examify_flutter/lib/**/widgets/**,\
examify_flutter/lib/**/models/**,\
examify_flutter/lib/**/generated/**,\
examify_flutter/lib/**/*.g.dart,\
examify_flutter/lib/**/*.freezed.dart,\
examify-backend/app/Http/Controllers/**,\
examify-backend/app/Models/**
