name: SonarQube CI

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarqube:
    name: SonarQube Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Install Flutter Dependencies
        working-directory: examify_flutter
        run: flutter pub get
        continue-on-error: true

      - name: Analyze Flutter Code
        working-directory: examify_flutter
        run: flutter analyze
        continue-on-error: true

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.4"
          extensions: fileinfo, gd, zip
          tools: composer

      - name: Install Laravel Dependencies
        working-directory: examify-backend
        run: composer install --no-interaction --prefer-dist
        continue-on-error: true

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v6
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
